name: receptar
description: "Flutter project as a school assignment"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  auto_route: ^9.2.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: SourGummy-Black
      fonts:
        - asset: assets/fonts/SourGummy/SourGummy-Black.ttf
          weight: 900
    - family: SourGummy-Regular
      fonts:
        - asset: assets/fonts/SourGummy/SourGummy-Regular.ttf
          weight: 400
    - family: SourGummy-Thin
      fonts:
        - asset: assets/fonts/SourGummy/SourGummy-Thin.ttf
          weight: 100
